name: Deploy

on:
  workflow_dispatch:
       
jobs: 
  deploy:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/github-script@v4
      with:
        script: |          
          const { data: approvals } = await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/approvals', {
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: context.runId
          })

          console.log(approvals);

          for (const approval of approvals) {
            if (approval.user.login == context.actor) {
              core.setFailed(`Deployment was approved by the same person (${context.actor}) who initiated the deployment.`);            
              return;
            }
          }
    - run: |
        echo "Deploying..."